http {
    # 启用WebSocket支持
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }
    
    server {
        listen 8058;
        
        location / {
            websocket_handler;  # 启用WebSocket处理
            
        }
    }
}