# 网关基本配置
[gateway]
ip = 192.168.40.129
port = 8088
# 单个进程承载连接的上限 小于1W或者大于100W就取默认值20W
fd_limit = 200000
# gwrcv的write的协程数，暂未使用(同一个fd在多协程下写会错乱，初步判断为micro_thread实现有问题)
co_count = 1000
# gwcliprc 绑定的核，目前仅限一个 不同的程序尽量不要绑定到同一个核上去
ccore_mask = 8
log_path = /var/log/tgg_gateway/
log_level = INFO
# 是否启用进程自动管理，1 是，0，否(意味着所有进程全部都需要手动启动)
auto_start = 1

# redis 配置
[redis]
addrs = 54.241.112.155:7001,54.241.112.155:7002
password = bZSCEI3VyV

# bwprc配置
[bwserver]
ip = 192.168.1.126
port = 8021
# 单个进程承载连接的上限 小于100或者大于10W就取默认值5K
fd_limit = 5000
co_count = 50
# gwbwprc 绑定的核，绑定的核数不一定要和进程数相等，多个进程绑一个核是没有问题的
bcore_mask = 16
process_count = 3
heart_beat = 5
secret_key = 
log_level = INFO

# register配置
[register]
ip = 192.168.1.126
port = 8021
log_level = INFO
